spring:
  application:
    name: doctor-service

  kafka:
    spring.json.trusted.packages: "*"
  main:
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://meeting-service:1012/eureka/  # Points to meeting-service container
  instance:
    prefer-ip-address: true
    hostname: doctor-service

server:
  port: 1011

logging:
  level:
    root: info


