spring:
  application:
    name: appointment-service

#  datasource:
#    url: jdbc:h2:mem:mydatabase
#    username: admin_viewer
#    password: password
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    database-platform: org.hibernate.dialect.H2Dialect

  sql:
      init:
        mode: always
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: org.com.doctorservice.dto.DoctorResponseDTO
    bootstrap-servers: kafka:9092


server:
  port: 1012

logging:
  level:
    root: info
